### ISSUE TITLE
Sample zip files errors MVVM Design Pattern in MVC Core - Part 1, Part 2, and Part 3

### ISSUE THREAD

**Issue by jamesperrin** [PaulDSheriff/Articles-CodeMagazine#2]
The is an error for all sample code zip files for the Use the MVVM Design Pattern in MVC Core - Part 1, Part 2, and Part 3.

![image](https://user-images.githubusercontent.com/1738333/96040763-b053f780-0e1f-11eb-981b-9a64753a1567.png)

**Comment by PaulDSheriff** [comment]
Hello James,

I just downloaded and extracted them fine using File Explorer in Windows. Are you on a different OS? Can you try a different ZIP extractor?

Paul

**Comment by jamesperrin** [comment]
I running Windows 10. I tried extracting using 7-zip and Windows extraction tool.
If you look at the file size, it's only 112 KB not the 1.9 MB indicated in the Git commit history.

![image](https://user-images.githubusercontent.com/1738333/96043493-e6937600-0e23-11eb-9124-c1ce5bacd46d.png)

**Comment by PaulDSheriff** [comment]
Can you delete the file and download it again? I just downloaded it and it is all working fine.

**Comment by jamesperrin** [comment]
Okay.
You have to click on the link titled "2020-07-Code_Magazine-MVVM-MVC-Core-Part3.zip".
Then, there is a download button for the actual zip file.
Kind of misleading, but I got the zip file.

Thanks
JP
